name: Publish to GHCR (latest)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to publish to GHCR"
        required: false
        default: "latest"

jobs:
  push_ghcr:
    name: Build and push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Prepare image ref
        id: prep
        run: |
          REPO_LC=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LC=$REPO_LC" >> $GITHUB_ENV
          echo "image_ref=ghcr.io/${REPO_LC}:${{ inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Save version info
        run: |
          echo "${{ inputs.tag }}" > VERSION

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.image_ref }}
